### Create Product

POST http://symfony.test/catalog/product
Content-Type: application/json

{
  "name": "Foo Product",
  "price": 123,
  "isAvailable": true
}

### Show Product

GET http://symfony.test/catalog/product/{intId}
Content-Type: application/json

### Create Cart

POST http://symfony.test/cart
Content-Type: application/json

### Show Cart

GET http://symfony.test/cart/{intId}
Content-Type: application/json

### Add Product To cart

PUT http://symfony.test/cart
Content-Type: application/json

{
  "cartId": 10,
  "productId": 20,
  "quantity": 3
}

### Remove Product From Cart

DELETE http://symfony.test/cart
Content-Type: application/json

{
  "cartItemId": 1,
  "cartId": 10
}

### Update Cart Item Quantity

PATCH http://symfony.test/cart/item
Content-Type: application/json

{
  "cartItemId": 6,
  "quantity": 12
}

### Create Address

POST http://symfony.test/address
Content-Type: application/json

{
  "person": {
    "firstName": "Jan",
    "lastName": "Nowak",
    "phoneNumber": "+48 123456789"
  },
  "region": {
    "regionName": "Podkarpacie",
    "postCode": "35-001",
    "countryCode": "PL",
    "city": "Rzeszów"
  },
  "street":{
    "streetName": "Plac Wolności",
    "streetNumber": "1"
  }
}

### Show Address

GET http://symfony.test/address/{intId}
Content-Type: application/json

### Add Address For cart

PUT http://symfony.test/cart/address
Content-Type: application/json

{
  "cartId":10,
  "addressId":1
}