### Create Product

POST http://symfony.test/catalog/product
Content-Type: application/json

{
  "name": "test 123 product",
  "price": 440,
  "isAvailable": true
}

### Show Product

GET http://symfony.test/catalog/product/1
Content-Type: application/json

### Create Cart

POST http://symfony.test/cart
Content-Type: application/json

### Show Cart

GET http://symfony.test/cart/1
Content-Type: application/json

### Add Product To cart

PUT http://symfony.test/cart
Content-Type: application/json

{
  "cartId": 12,
  "productId": 10,
  "quantity": 3
}

### Remove Product From Cart

DELETE http://symfony.test/cart
Content-Type: application/json

{
  "cartItemId": 11,
  "cartId": 12
}

### Update Cart Item Quantity

PATCH http://symfony.test/cart/item
Content-Type: application/json

{
  "cartItemId": 8,
  "quantity": 5
}

### Create Address

POST http://symfony.test/address
Content-Type: application/json

{
  "person": {
    "firstName": "Jan",
    "lastName": "Nowak",
    "phoneNumber": "+48 123"
  },
  "region": {
    "regionName": "Podkarpacie",
    "postCode": "35-001",
    "countryCode": "PL",
    "city": "Rzeszów"
  },
  "street":{
    "streetName": "Plac Wolności",
    "streetNumber": "1"
  }
}

### Show Address

GET http://symfony.test/address/1
Content-Type: application/json

### Add Address For cart

PUT http://symfony.test/cart/address
Content-Type: application/json

{
  "cartId":1,
  "addressId":1
}